### ISSUE TITLE
Draw PTM in another Colour 

### ISSUE THREAD

**Issue by ypriverol** [multiomics/mslookup#3]
@shabai517 next step it to draw the peptide ptms using a different color similar to PRIDE.

**Comment by shabai517** [comment]
I need to know the principle about how to decide the color for different PTMs.

**Comment by ypriverol** [comment]
Same color (red) like the pattern we used in PRIDE 

<img width="513" alt="Screen Shot 2020-09-05 at 15 13 17" src="https://user-images.githubusercontent.com/52113/92306878-6bb87f00-ef8a-11ea-9ccc-ec8265c7d83e.png">
 
and when you hover we should show the name of the PTM.

**Comment by ypriverol** [comment]
First prototype works.
